### ISSUE TITLE
bower not present as a package

### ISSUE THREAD

**Issue by hkrank** [amazingSurge/jquery-asChoice#3]
where is the jquery-asChoice on bower ?

**Comment by amazingSurge** [comment]
Hi, we will add to bower repository soon. Now you can try use 

bower install git@github.com:amazingSurge/jquery-asChoice.git

Regards

**Comment by hkrank** [comment]
Hello,

thanks for your email.

Looking forward to hear soon from you guys.

Best regards.

Hendrik

**Comment by amazingSurge** [comment]
it's available now.
